/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dados.ItemAcervo;
import dados.Livro;
import dados.Revista;
import dados.Emprestimo;
import negocios.GerenciadorBiblioteca;
import negocios.ItemIndisponivelException;
import negocios.ItemNaoEncontradoException;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Guilherme
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());

    /**
     * Creates new form NewJFrame
     */
    
    private GerenciadorBiblioteca gerenciador = new GerenciadorBiblioteca();
    
    public TelaPrincipal(GerenciadorBiblioteca gerenciador) {
        this.gerenciador = gerenciador;
        gerenciador.carregarAcervo();
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                gerenciador.salvarAcervo();
                System.exit(0);
            }
        });
        setLocationRelativeTo(null);
        atualizarTabela();
        if (!gerenciador.isAdministrador()) {
            btnCadastrarLivro.setEnabled(false);
            btnCadastrarRevista.setEnabled(false);
        }
    }

    private void atualizarTabela() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        for (ItemAcervo item : gerenciador.getAcervo()) {
            String status;
            if (item instanceof Livro){
                Livro livro = (Livro) item;
                if (livro.isDisponivel()){
                    status = "Disponivel (" + livro.getQuantidade() + ")";
                } else {
                    status = "Indisponivel";
                }
            } else if (item instanceof Revista){
                Revista revista = (Revista) item;
                if (revista.isDisponivel()){
                    status = "Disponivel (" + revista.getQuantidade() + ")";
                } else {
                    status = "Indisponivel";
                }
            } else {
                status = "-";
            }
            
            model.addRow(new Object[]{
                item.getTipo(),
                item.getTitulo(),
                item.getAutor(),
                item.getAno(),
                status
            });
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCadastrarLivro = new javax.swing.JButton();
        btnCadastrarRevista = new javax.swing.JButton();
        btnEmprestar = new javax.swing.JButton();
        btnDevolver = new javax.swing.JButton();
        btnVerEmprestimos = new javax.swing.JButton();
        tabelaAcervo = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBackground(new java.awt.Color(24, 95, 165));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(246, 246, 246));
        jLabel1.setText("Sistema de Biblioteca");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCadastrarLivro.setBackground(new java.awt.Color(24, 95, 165));
        btnCadastrarLivro.setForeground(new java.awt.Color(246, 246, 246));
        btnCadastrarLivro.setText("Cadastrar Livro");
        btnCadastrarLivro.addActionListener(this::btnCadastrarLivroActionPerformed);

        btnCadastrarRevista.setBackground(new java.awt.Color(24, 95, 165));
        btnCadastrarRevista.setForeground(new java.awt.Color(246, 246, 246));
        btnCadastrarRevista.setText("Cadastrar Revista");
        btnCadastrarRevista.addActionListener(this::btnCadastrarRevistaActionPerformed);

        btnEmprestar.setBackground(new java.awt.Color(15, 110, 86));
        btnEmprestar.setForeground(new java.awt.Color(246, 246, 246));
        btnEmprestar.setText("Emprestar");
        btnEmprestar.addActionListener(this::btnEmprestarActionPerformed);

        btnDevolver.setBackground(new java.awt.Color(59, 109, 17));
        btnDevolver.setForeground(new java.awt.Color(246, 246, 246));
        btnDevolver.setText("Devolver");
        btnDevolver.addActionListener(this::btnDevolverActionPerformed);

        btnVerEmprestimos.setBackground(new java.awt.Color(133, 79, 11));
        btnVerEmprestimos.setForeground(new java.awt.Color(246, 246, 246));
        btnVerEmprestimos.setText("Ver Empréstimos");
        btnVerEmprestimos.addActionListener(this::btnVerEmprestimosActionPerformed);

        tabelaAcervo.setBackground(new java.awt.Color(0, 0, 0));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tipo", "Título", "Autor", "Ano", "Status"
            }
        ));
        tabelaAcervo.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabelaAcervo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCadastrarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCadastrarRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEmprestar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVerEmprestimos, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarLivro)
                    .addComponent(btnCadastrarRevista)
                    .addComponent(btnEmprestar)
                    .addComponent(btnDevolver)
                    .addComponent(btnVerEmprestimos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabelaAcervo, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmprestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmprestarActionPerformed
        DialogEmprestar dialog = new DialogEmprestar(this, gerenciador);
        dialog.setVisible(true);
        atualizarTabela();
    }//GEN-LAST:event_btnEmprestarActionPerformed

    private void btnCadastrarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarLivroActionPerformed
        DialogCadastrarLivro dialog = new DialogCadastrarLivro(this, gerenciador);
        dialog.setVisible(true);
        atualizarTabela();
    }//GEN-LAST:event_btnCadastrarLivroActionPerformed

    private void btnCadastrarRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarRevistaActionPerformed
        DialogCadastrarRevista dialog = new DialogCadastrarRevista(this, gerenciador);
        dialog.setVisible(true);
        atualizarTabela();
    }//GEN-LAST:event_btnCadastrarRevistaActionPerformed

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
        DialogDevolver dialog = new DialogDevolver(this, gerenciador);
        dialog.setVisible(true);
        atualizarTabela();
    }//GEN-LAST:event_btnDevolverActionPerformed

    private void btnVerEmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEmprestimosActionPerformed
        StringBuilder sb = new StringBuilder();

        if (gerenciador.getEmprestimos().isEmpty()) {
            sb.append("Nenhum empréstimo registrado.");
        } else {
            for (Emprestimo emp : gerenciador.getEmprestimos()) {
                sb.append("Usuário: ").append(emp.getNomeUsuario()).append("\n");
                sb.append("Item: ").append(emp.getItem().getTitulo()).append("\n");
                sb.append("Retirado: ").append(emp.getDataEmprestimo()).append("\n");
                sb.append("Devolução prevista: ").append(emp.getDataPrevistaDevolucao()).append("\n");

                if (emp.isDevolvido()) {
                    sb.append("Devolvido em: ").append(emp.getDataDevolucao()).append("\n");
                } else {
                    sb.append("Status: Em aberto\n");
                }

                sb.append("Multa: R$ ").append(String.format("%.2f", emp.calcularMulta())).append("\n");
                sb.append("----------------------\n");
            }
        }

        JOptionPane.showMessageDialog(this, sb.toString(), "Empréstimos", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnVerEmprestimosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarLivro;
    private javax.swing.JButton btnCadastrarRevista;
    private javax.swing.JButton btnDevolver;
    private javax.swing.JButton btnEmprestar;
    private javax.swing.JButton btnVerEmprestimos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane tabelaAcervo;
    // End of variables declaration//GEN-END:variables
}
